server:
  port: 9000

spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          client1:
            registration:
              client-id: client1
              client-secret: "{noop}secret"  # or use {bcrypt} for encoded
              client-authentication-methods:
                - client_secret_basic
                - client_secret_post
              redirect-uris:
                - "http://localhost:8081/login/oauth2/code/client1"
              scopes:
                - "openid"
                - "read"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              require-authorization-consent: false
              require-proof-key: false

logging:
  level:
    org.springframework.security: DEBUG
